/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package traslados.impuestos;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class comprobante extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"comprobante\",\"namespace\":\"traslados.impuestos\",\"fields\":[{\"name\":\"traslado\",\"type\":{\"type\":\"record\",\"name\":\"comprobante\",\"namespace\":\"traslado.traslados.impuestos\",\"fields\":[{\"name\":\"impuesto\",\"type\":\"string\"},{\"name\":\"tasa\",\"type\":\"int\"},{\"name\":\"importe\",\"type\":\"double\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public traslado.traslados.impuestos.comprobante traslado;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public comprobante() {}

  /**
   * All-args constructor.
   */
  public comprobante(traslado.traslados.impuestos.comprobante traslado) {
    this.traslado = traslado;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return traslado;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: traslado = (traslado.traslados.impuestos.comprobante)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'traslado' field.
   */
  public traslado.traslados.impuestos.comprobante getTraslado() {
    return traslado;
  }

  /**
   * Sets the value of the 'traslado' field.
   * @param value the value to set.
   */
  public void setTraslado(traslado.traslados.impuestos.comprobante value) {
    this.traslado = value;
  }

  /** Creates a new comprobante RecordBuilder */
  public static traslados.impuestos.comprobante.Builder newBuilder() {
    return new traslados.impuestos.comprobante.Builder();
  }
  
  /** Creates a new comprobante RecordBuilder by copying an existing Builder */
  public static traslados.impuestos.comprobante.Builder newBuilder(traslados.impuestos.comprobante.Builder other) {
    return new traslados.impuestos.comprobante.Builder(other);
  }
  
  /** Creates a new comprobante RecordBuilder by copying an existing comprobante instance */
  public static traslados.impuestos.comprobante.Builder newBuilder(traslados.impuestos.comprobante other) {
    return new traslados.impuestos.comprobante.Builder(other);
  }
  
  /**
   * RecordBuilder for comprobante instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<comprobante>
    implements org.apache.avro.data.RecordBuilder<comprobante> {

    private traslado.traslados.impuestos.comprobante traslado;

    /** Creates a new Builder */
    private Builder() {
      super(traslados.impuestos.comprobante.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(traslados.impuestos.comprobante.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.traslado)) {
        this.traslado = data().deepCopy(fields()[0].schema(), other.traslado);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing comprobante instance */
    private Builder(traslados.impuestos.comprobante other) {
            super(traslados.impuestos.comprobante.SCHEMA$);
      if (isValidValue(fields()[0], other.traslado)) {
        this.traslado = data().deepCopy(fields()[0].schema(), other.traslado);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'traslado' field */
    public traslado.traslados.impuestos.comprobante getTraslado() {
      return traslado;
    }
    
    /** Sets the value of the 'traslado' field */
    public traslados.impuestos.comprobante.Builder setTraslado(traslado.traslados.impuestos.comprobante value) {
      validate(fields()[0], value);
      this.traslado = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'traslado' field has been set */
    public boolean hasTraslado() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'traslado' field */
    public traslados.impuestos.comprobante.Builder clearTraslado() {
      traslado = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public comprobante build() {
      try {
        comprobante record = new comprobante();
        record.traslado = fieldSetFlags()[0] ? this.traslado : (traslado.traslados.impuestos.comprobante) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
