/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package impuestos;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class comprobante extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"comprobante\",\"namespace\":\"impuestos\",\"fields\":[{\"name\":\"traslados\",\"type\":{\"type\":\"record\",\"name\":\"comprobante\",\"namespace\":\"traslados.impuestos\",\"fields\":[{\"name\":\"traslado\",\"type\":{\"type\":\"record\",\"name\":\"comprobante\",\"namespace\":\"traslado.traslados.impuestos\",\"fields\":[{\"name\":\"impuesto\",\"type\":\"string\"},{\"name\":\"tasa\",\"type\":\"int\"},{\"name\":\"importe\",\"type\":\"double\"}]}}]}},{\"name\":\"totalImpuestosTrasladados\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public traslados.impuestos.comprobante traslados;
  @Deprecated public double totalImpuestosTrasladados;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public comprobante() {}

  /**
   * All-args constructor.
   */
  public comprobante(traslados.impuestos.comprobante traslados, java.lang.Double totalImpuestosTrasladados) {
    this.traslados = traslados;
    this.totalImpuestosTrasladados = totalImpuestosTrasladados;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return traslados;
    case 1: return totalImpuestosTrasladados;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: traslados = (traslados.impuestos.comprobante)value$; break;
    case 1: totalImpuestosTrasladados = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'traslados' field.
   */
  public traslados.impuestos.comprobante getTraslados() {
    return traslados;
  }

  /**
   * Sets the value of the 'traslados' field.
   * @param value the value to set.
   */
  public void setTraslados(traslados.impuestos.comprobante value) {
    this.traslados = value;
  }

  /**
   * Gets the value of the 'totalImpuestosTrasladados' field.
   */
  public java.lang.Double getTotalImpuestosTrasladados() {
    return totalImpuestosTrasladados;
  }

  /**
   * Sets the value of the 'totalImpuestosTrasladados' field.
   * @param value the value to set.
   */
  public void setTotalImpuestosTrasladados(java.lang.Double value) {
    this.totalImpuestosTrasladados = value;
  }

  /** Creates a new comprobante RecordBuilder */
  public static impuestos.comprobante.Builder newBuilder() {
    return new impuestos.comprobante.Builder();
  }
  
  /** Creates a new comprobante RecordBuilder by copying an existing Builder */
  public static impuestos.comprobante.Builder newBuilder(impuestos.comprobante.Builder other) {
    return new impuestos.comprobante.Builder(other);
  }
  
  /** Creates a new comprobante RecordBuilder by copying an existing comprobante instance */
  public static impuestos.comprobante.Builder newBuilder(impuestos.comprobante other) {
    return new impuestos.comprobante.Builder(other);
  }
  
  /**
   * RecordBuilder for comprobante instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<comprobante>
    implements org.apache.avro.data.RecordBuilder<comprobante> {

    private traslados.impuestos.comprobante traslados;
    private double totalImpuestosTrasladados;

    /** Creates a new Builder */
    private Builder() {
      super(impuestos.comprobante.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(impuestos.comprobante.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.traslados)) {
        this.traslados = data().deepCopy(fields()[0].schema(), other.traslados);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalImpuestosTrasladados)) {
        this.totalImpuestosTrasladados = data().deepCopy(fields()[1].schema(), other.totalImpuestosTrasladados);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing comprobante instance */
    private Builder(impuestos.comprobante other) {
            super(impuestos.comprobante.SCHEMA$);
      if (isValidValue(fields()[0], other.traslados)) {
        this.traslados = data().deepCopy(fields()[0].schema(), other.traslados);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalImpuestosTrasladados)) {
        this.totalImpuestosTrasladados = data().deepCopy(fields()[1].schema(), other.totalImpuestosTrasladados);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'traslados' field */
    public traslados.impuestos.comprobante getTraslados() {
      return traslados;
    }
    
    /** Sets the value of the 'traslados' field */
    public impuestos.comprobante.Builder setTraslados(traslados.impuestos.comprobante value) {
      validate(fields()[0], value);
      this.traslados = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'traslados' field has been set */
    public boolean hasTraslados() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'traslados' field */
    public impuestos.comprobante.Builder clearTraslados() {
      traslados = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'totalImpuestosTrasladados' field */
    public java.lang.Double getTotalImpuestosTrasladados() {
      return totalImpuestosTrasladados;
    }
    
    /** Sets the value of the 'totalImpuestosTrasladados' field */
    public impuestos.comprobante.Builder setTotalImpuestosTrasladados(double value) {
      validate(fields()[1], value);
      this.totalImpuestosTrasladados = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'totalImpuestosTrasladados' field has been set */
    public boolean hasTotalImpuestosTrasladados() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'totalImpuestosTrasladados' field */
    public impuestos.comprobante.Builder clearTotalImpuestosTrasladados() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public comprobante build() {
      try {
        comprobante record = new comprobante();
        record.traslados = fieldSetFlags()[0] ? this.traslados : (traslados.impuestos.comprobante) defaultValue(fields()[0]);
        record.totalImpuestosTrasladados = fieldSetFlags()[1] ? this.totalImpuestosTrasladados : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
