/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package regimenFiscal.emisor;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class comprobante extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"comprobante\",\"namespace\":\"regimenFiscal.emisor\",\"fields\":[{\"name\":\"Regimen\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence Regimen;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public comprobante() {}

  /**
   * All-args constructor.
   */
  public comprobante(java.lang.CharSequence Regimen) {
    this.Regimen = Regimen;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Regimen;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Regimen = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Regimen' field.
   */
  public java.lang.CharSequence getRegimen() {
    return Regimen;
  }

  /**
   * Sets the value of the 'Regimen' field.
   * @param value the value to set.
   */
  public void setRegimen(java.lang.CharSequence value) {
    this.Regimen = value;
  }

  /** Creates a new comprobante RecordBuilder */
  public static regimenFiscal.emisor.comprobante.Builder newBuilder() {
    return new regimenFiscal.emisor.comprobante.Builder();
  }
  
  /** Creates a new comprobante RecordBuilder by copying an existing Builder */
  public static regimenFiscal.emisor.comprobante.Builder newBuilder(regimenFiscal.emisor.comprobante.Builder other) {
    return new regimenFiscal.emisor.comprobante.Builder(other);
  }
  
  /** Creates a new comprobante RecordBuilder by copying an existing comprobante instance */
  public static regimenFiscal.emisor.comprobante.Builder newBuilder(regimenFiscal.emisor.comprobante other) {
    return new regimenFiscal.emisor.comprobante.Builder(other);
  }
  
  /**
   * RecordBuilder for comprobante instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<comprobante>
    implements org.apache.avro.data.RecordBuilder<comprobante> {

    private java.lang.CharSequence Regimen;

    /** Creates a new Builder */
    private Builder() {
      super(regimenFiscal.emisor.comprobante.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(regimenFiscal.emisor.comprobante.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Regimen)) {
        this.Regimen = data().deepCopy(fields()[0].schema(), other.Regimen);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing comprobante instance */
    private Builder(regimenFiscal.emisor.comprobante other) {
            super(regimenFiscal.emisor.comprobante.SCHEMA$);
      if (isValidValue(fields()[0], other.Regimen)) {
        this.Regimen = data().deepCopy(fields()[0].schema(), other.Regimen);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'Regimen' field */
    public java.lang.CharSequence getRegimen() {
      return Regimen;
    }
    
    /** Sets the value of the 'Regimen' field */
    public regimenFiscal.emisor.comprobante.Builder setRegimen(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Regimen = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Regimen' field has been set */
    public boolean hasRegimen() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Regimen' field */
    public regimenFiscal.emisor.comprobante.Builder clearRegimen() {
      Regimen = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public comprobante build() {
      try {
        comprobante record = new comprobante();
        record.Regimen = fieldSetFlags()[0] ? this.Regimen : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
